package latina.vista;

public enum Eventos {
    REGISTRAR_ROL,
    ASIGNAR_TURNO,
    OBTENER_TURNOS_POR_DIA,
    OBTENER_EMPLEADOS_DISPONIBLES,
    REGISTRAR_EMPLEADO,
    OBTENER_TODOS_LOS_EMPLEADOS,
    REGISTRAR_DISPONIBILIDAD
}
