package latina.vista;

public enum Eventos {
    REGISTRAR_ROL,
    ASIGNAR_TURNO,
    OBTENER_TURNOS_POR_DIA,
    OBTENER_EMPLEADOS_DISPONIBLES,
    REGISTRAR_EMPLEADO,
    OBTENER_TODOS_LOS_EMPLEADOS,
    REGISTRAR_DISPONIBILIDAD,
    OBTENER_TODOS_LOS_ROLES,
    REGISTRAR_TURNO,
    OBTENER_TURNOS_SEMANALES,
    INICIAR_SESION,
    INICIALIZAR_GERENTE
}
